changelog:
  categories:
    - title: Features
      labels:
        - "RN: MAJOR FEATURE"
        - "RN: MINOR FEATURE"
        - "RN: MAJOR FEATURE - CUSTOM BUILD"
        - "RN: MINOR FEATURE - CUSTOM BUILD"
    - title: Improvements
      labels:
        - "RN: IMPROVEMENT"
        - "RN: IMPROVEMENT - CUSTOM BUILD"
        - "RN: REFACTORING"
    - title: Fixes
<<<<<<< HEAD
      labels: 
=======
      labels:
>>>>>>> 76e02ed47cfbb341a780befd7d0dc21db30a5b60
        - "RN: BUGFIX"
        - "RN: BUGFIX - CUSTOM BUILD"
    - title: Targets
      labels:
<<<<<<< HEAD
        - "RN: NEW BOARD SUPPORT"
=======
        - "RN: NEW BOARD SUPPORT"
>>>>>>> 76e02ed47cfbb341a780befd7d0dc21db30a5b60
