name: Build QGroundControl Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get code from GitHub
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        arch: 'win64_msvc2019_64'

    - name: Create build folder
      run: mkdir build

    - name: Configure project (CMake)
      run: |
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Build EXE
      run: cmake --build build --config Release

    - name: Upload EXE file
      uses: actions/upload-artifact@v4
      with:
        name: QGroundControl-Windows
        path: build/Release/
